name: CI

on:
  push:
    branches: [ main, develop, feat/wallet_core ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install root dependencies
      run: npm install

    - name: Install frontend dependencies
      run: cd frontend && npm install

    - name: Install backend dependencies
      run: cd backend && npm install

    - name: Install contracts dependencies
      run: cd contracts && npm install

    - name: Run root linting
      run: npm run lint

    - name: Run frontend linting
      run: cd frontend && npm run lint

    - name: Run backend linting
      run: cd backend && npm run lint

    - name: Run frontend type checking
      run: cd frontend && npm run type-check

    - name: Run backend type checking
      run: cd backend && npm run type-check

    - name: Run frontend tests
      run: cd frontend && npm run test

    - name: Run backend tests
      run: cd backend && npm run test

    - name: Run contract tests
      run: cd contracts && npm run test

    - name: Build frontend
      run: cd frontend && npm run build

    - name: Build backend
      run: cd backend && npm run build

    - name: Compile contracts
      run: cd contracts && npm run compile

    - name: Upload frontend build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build-${{ matrix.node-version }}
        path: frontend/dist/
        retention-days: 7

    - name: Upload backend build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-build-${{ matrix.node-version }}
        path: backend/dist/
        retention-days: 7

  security:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install root dependencies
      run: npm install

    - name: Install frontend dependencies
      run: cd frontend && npm install

    - name: Install backend dependencies
      run: cd backend && npm install

    - name: Install contracts dependencies
      run: cd contracts && npm install

    - name: Run root security audit
      run: npm audit --audit-level=high

    - name: Run frontend security audit
      run: cd frontend && npm audit --audit-level=high

    - name: Run backend security audit
      run: cd backend && npm audit --audit-level=high

    - name: Run contracts security audit
      run: cd contracts && npm audit --audit-level=high

    - name: Run security audit with JSON output
      run: npm audit --audit-level=high --json > audit-report.json || true

    - name: Upload security report
      uses: actions/upload-artifact@v4
      with:
        name: security-audit-report
        path: audit-report.json
        retention-days: 30
